package com.agenda.model;
// Generated 19-abr-2015 21:47:32 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Notificacion generated by hbm2java
 */
@Entity
@Table(name="notificacion"
    ,catalog="agenda"
)
public class Notificacion  implements java.io.Serializable {


     private int notificacionId;
     private Tarea tarea;

    public Notificacion() {
    }

    public Notificacion(int notificacionId, Tarea tarea) {
       this.notificacionId = notificacionId;
       this.tarea = tarea;
    }
   
     @Id 

    
    @Column(name="notificacion_id", unique=true, nullable=false)
    public int getNotificacionId() {
        return this.notificacionId;
    }
    
    public void setNotificacionId(int notificacionId) {
        this.notificacionId = notificacionId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tarea_tarea_id", nullable=false)
    public Tarea getTarea() {
        return this.tarea;
    }
    
    public void setTarea(Tarea tarea) {
        this.tarea = tarea;
    }




}


