package com.agenda.model;
// Generated 19-abr-2015 21:47:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proyecto generated by hbm2java
 */
@Entity
@Table(name="proyecto"
    ,catalog="agenda"
)
public class Proyecto  implements java.io.Serializable {


     private Integer proyectoId;
     private String nombre;
     private String descripcion;
     private Set tareas = new HashSet(0);

    public Proyecto() {
    }

	
    public Proyecto(String nombre, String descripcion) {
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Proyecto(String nombre, String descripcion, Set tareas) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.tareas = tareas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="proyecto_id", unique=true, nullable=false)
    public Integer getProyectoId() {
        return this.proyectoId;
    }
    
    public void setProyectoId(Integer proyectoId) {
        this.proyectoId = proyectoId;
    }

    
    @Column(name="nombre", nullable=false, length=65)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proyecto")
    public Set getTareas() {
        return this.tareas;
    }
    
    public void setTareas(Set tareas) {
        this.tareas = tareas;
    }




}


