package com.agenda.model;
// Generated 19-abr-2015 21:47:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tarea generated by hbm2java
 */
@Entity
@Table(name="tarea"
    ,catalog="agenda"
)
public class Tarea  implements java.io.Serializable {


     private Integer tareaId;
     private Persona persona;
     private Proyecto proyecto;
     private String nombre;
     private String descripcion;
     private Date fecha;
     private int ejecucion;
     private boolean estadoTarea;
     private Set notificacions = new HashSet(0);

    public Tarea() {
    }

	
    public Tarea(Persona persona, Proyecto proyecto, String nombre, String descripcion, Date fecha, int ejecucion, boolean estadoTarea) {
        this.persona = persona;
        this.proyecto = proyecto;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.fecha = fecha;
        this.ejecucion = ejecucion;
        this.estadoTarea = estadoTarea;
    }
    public Tarea(Persona persona, Proyecto proyecto, String nombre, String descripcion, Date fecha, int ejecucion, boolean estadoTarea, Set notificacions) {
       this.persona = persona;
       this.proyecto = proyecto;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.ejecucion = ejecucion;
       this.estadoTarea = estadoTarea;
       this.notificacions = notificacions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tarea_id", unique=true, nullable=false)
    public Integer getTareaId() {
        return this.tareaId;
    }
    
    public void setTareaId(Integer tareaId) {
        this.tareaId = tareaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="persona_id", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proyecto_id", nullable=false)
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }

    
    @Column(name="nombre", nullable=false, length=65)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", nullable=false, length=16777215)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="ejecucion", nullable=false)
    public int getEjecucion() {
        return this.ejecucion;
    }
    
    public void setEjecucion(int ejecucion) {
        this.ejecucion = ejecucion;
    }

    
    @Column(name="estado_tarea", nullable=false)
    public boolean isEstadoTarea() {
        return this.estadoTarea;
    }
    
    public void setEstadoTarea(boolean estadoTarea) {
        this.estadoTarea = estadoTarea;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tarea")
    public Set getNotificacions() {
        return this.notificacions;
    }
    
    public void setNotificacions(Set notificacions) {
        this.notificacions = notificacions;
    }




}


